### ISSUE TITLE
Error in indent/rnoweb if indentexpr for tex is empty

### ISSUE THREAD

**Issue by jfrankenau** [jalvesaq/R-Vim-runtime#9]
I am using [vimtex](https://github.com/lervag/vimtex) which provides the option to disable auto indentation by setting `g:vimtex_indent_enabled`.

When editing a `.rnoweb` file this will result in the following error:

```
Error detected while processing /usr/share/nvim/runtime/indent/rnoweb.vim:
line   12:
E475: Invalid argument:
E706: Variable type mismatch for: s:TeXIndent
```

I believe this is due to `indentexpr` not being set anymore during `runtime/tex.vim`.

**Comment by jalvesaq** [comment]
I fixed the bug, but I am not sure if the result is what you want because the rnoweb indent script has to indent the LaTeX. What I did was to return the current line indentation, that is, spaces and tabs must added and deleted manually if you want indentation, and 'smartindent' and 'cindent' seems to be ignored. Please, install R-Vim-runtime and tell me whether the indentation is OK now.

**Comment by jfrankenau** [comment]
Yes, simply returning the current line indentation seems like a sensible choice in this edge case. I've just installed the R-Vim-runtime but now I get the following:

```
Error detected while processing /home/tsuflux/.vim/plugged/R-Vim-runtime/indent/rnoweb.vim:
line   18:
E705: Variable name conflicts with existing function: s:TeXIndent
```

I would have thought that the if-else statement would prevent this. Deleting the global runtime files for R didn't help.

**Comment by jalvesaq** [comment]
Thanks for the feedback! Please, check whether it works now.

**Comment by jfrankenau** [comment]
Thank you. VimL is an odd language. Now everything works as expected: LaTeX indentation is off but R chunks are still indented.
